#!/usr/bin/env bash
# Interactive, secure .env setup for notify-hub.
#
# NOTE (DBCH-10): this only seeds the FIRST boot. Channels/profiles written
# here are read exactly once, when the service starts against an empty
# SQLite database (spec DBCH-03) -- after that, the DB is the source of
# truth and ongoing management (add/edit/delete channels, change profile
# defaults) happens live in the admin panel (http://127.0.0.1:8081), not by
# re-running this script or hand-editing .env.
#
# - Secrets are read with hidden input (never echoed, never in shell history).
# - Press Enter to skip any channel you don't want; CHANNELS_ENABLED is built
#   from what you actually filled in.
# - Generates a strong gateway token for you (openssl rand).
# - Writes .env with chmod 600 (owner read/write only).
#
# Usage: ./scripts/setup-env.sh [output-path]   (default: ./.env)

set -euo pipefail

OUT="${1:-.env}"

if [[ -e "$OUT" ]]; then
  BACKUP="$OUT.backup.$(date +%Y%m%d%H%M%S)"
  cp "$OUT" "$BACKUP"
  echo "Existing $OUT backed up to $BACKUP"
fi

ask() { # ask <prompt> [default] -> visible input
  local prompt="$1" default="${2:-}" val
  read -rp "$prompt${default:+ [$default]}: " val || true
  printf '%s' "${val:-$default}"
}

ask_secret() { # ask_secret <prompt> -> hidden input (Enter to skip)
  local prompt="$1" val
  read -rsp "$prompt (hidden, Enter to skip): " val || true
  echo >&2
  printf '%s' "$val"
}

echo "== notify-hub setup =="
echo "Fill only the channels you want. Anything skipped stays disabled."
echo

ENABLED=()
LINES=()

# --- ntfy ---
echo "-- ntfy (easiest: install the ntfy app, subscribe to a secret topic) --"
NTFY_TOPIC="$(ask_secret 'ntfy topic (acts as a password — make it unguessable)')"
if [[ -n "$NTFY_TOPIC" ]]; then
  NTFY_URL="$(ask 'ntfy server URL' 'https://ntfy.sh')"
  ENABLED+=(ntfy)
  LINES+=("NTFY_URL=$NTFY_URL" "NTFY_TOPIC=$NTFY_TOPIC")
fi
echo

# --- Telegram ---
echo "-- Telegram (token from @BotFather; chat id from /getUpdates) --"
TELEGRAM_BOT_TOKEN="$(ask_secret 'Telegram bot token')"
if [[ -n "$TELEGRAM_BOT_TOKEN" ]]; then
  TELEGRAM_CHAT_ID="$(ask 'Telegram chat id')"
  ENABLED+=(telegram)
  LINES+=("TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID")
fi
echo

# --- Email ---
echo "-- Email / SMTP (e.g. Gmail app password) --"
SMTP_PASS="$(ask_secret 'SMTP password / app password')"
if [[ -n "$SMTP_PASS" ]]; then
  SMTP_HOST="$(ask 'SMTP host' 'smtp.gmail.com')"
  SMTP_PORT="$(ask 'SMTP port' '587')"
  SMTP_USER="$(ask 'SMTP user (your email)')"
  EMAIL_TO="$(ask 'Send notifications to (email)' "$SMTP_USER")"
  ENABLED+=(email)
  LINES+=("SMTP_HOST=$SMTP_HOST" "SMTP_PORT=$SMTP_PORT" "SMTP_USER=$SMTP_USER" "SMTP_PASS=$SMTP_PASS" "EMAIL_TO=$EMAIL_TO")
fi
echo

# --- Slack ---
echo "-- Slack (app -> Incoming Webhooks -> webhook URL) --"
SLACK_WEBHOOK_URL="$(ask_secret 'Slack webhook URL')"
if [[ -n "$SLACK_WEBHOOK_URL" ]]; then
  ENABLED+=(slack)
  LINES+=("SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL")
fi
echo

# --- Discord ---
echo "-- Discord (channel -> Integrations -> Webhooks -> copy URL) --"
DISCORD_WEBHOOK_URL="$(ask_secret 'Discord webhook URL')"
if [[ -n "$DISCORD_WEBHOOK_URL" ]]; then
  ENABLED+=(discord)
  LINES+=("DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL")
fi
echo

# --- WhatsApp (CallMeBot) ---
echo "-- WhatsApp via CallMeBot (message their bot once to get an apikey) --"
WHATSAPP_APIKEY="$(ask_secret 'CallMeBot apikey')"
if [[ -n "$WHATSAPP_APIKEY" ]]; then
  WHATSAPP_PHONE="$(ask 'Your WhatsApp phone (intl format, e.g. +5511999999999)')"
  ENABLED+=(whatsapp)
  LINES+=("WHATSAPP_PHONE=$WHATSAPP_PHONE" "WHATSAPP_APIKEY=$WHATSAPP_APIKEY")
fi
echo

# --- Generic webhook ---
echo "-- Generic webhook (POSTs the notification JSON to any URL; optional) --"
WEBHOOK_URL="$(ask_secret 'Webhook URL')"
if [[ -n "$WEBHOOK_URL" ]]; then
  ENABLED+=(webhook)
  LINES+=("WEBHOOK_URL=$WEBHOOK_URL")
fi
echo

if [[ ${#ENABLED[@]} -eq 0 ]]; then
  echo "No channels configured — nothing to write. Run again and fill at least one." >&2
  exit 1
fi

CHANNELS_CSV="$(IFS=,; echo "${ENABLED[*]}")"

# --- Gateway token / profile ---
PROFILE_NAME="$(ask 'Profile name for your token' 'me')"
GATEWAY_TOKEN="$(openssl rand -hex 24)"
DEFAULT_CHANNELS="$(ask "Default channels for this token" "$CHANNELS_CSV")"

{
  echo "# Generated by scripts/setup-env.sh on $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "PORT=8080"
  echo "REDIS_URL=redis://redis:6379"
  echo "TOKENS=$PROFILE_NAME:$GATEWAY_TOKEN:$DEFAULT_CHANNELS"
  echo "CHANNELS_ENABLED=$CHANNELS_CSV"
  printf '%s\n' "${LINES[@]}"
  echo "RETRY_ATTEMPTS=5"
  echo "RETRY_BACKOFF_MS=2000"
} > "$OUT"
chmod 600 "$OUT"

echo
echo "== Done =="
echo "Wrote $OUT (chmod 600). Channels enabled: $CHANNELS_CSV"
echo
echo "Your gateway token (for the Claude Code hook / MCP / curl — this is the"
echo "ONLY secret any client needs; channel credentials stay in $OUT):"
echo
echo "  export NOTIFY_URL=\"http://localhost:8080/notify\""
echo "  export NOTIFY_TOKEN=\"$GATEWAY_TOKEN\""
echo
echo "Add those two lines to your ~/.zshrc (or ~/.bashrc), then:"
echo "  docker compose up -d --build"
echo "  curl http://localhost:8080/health"
