/**
 * Tests derive from spec ADMIN-02/ADMIN-03 + Edge Cases: round-trip
 * (parse(serialize(cfg)) deep-equals cfg), unknown/extra-key preservation
 * (PORT, REDIS_URL, RETRY_*, custom), and "missing file -> empty model".
 */
import { describe, expect, it } from 'vitest'
import {
  parseAdminConfig,
  serializeAdminConfig,
  type AdminConfig,
  type ChannelSchema
} from './admin-config.js'

const registry: Record<string, ChannelSchema> = {
  ntfy: { requiredConfig: ['NTFY_URL', 'NTFY_TOPIC'] },
  slack: { requiredConfig: ['SLACK_WEBHOOK_URL'] }
}

describe('parseAdminConfig', () => {
  it('returns an empty model (all channels present, disabled, blank) when the file does not exist yet (edge case)', () => {
    const cfg = parseAdminConfig(null, registry)

    expect(cfg).toEqual({
      channels: {
        ntfy: { enabled: false, values: { NTFY_URL: '', NTFY_TOPIC: '' } },
        slack: { enabled: false, values: { SLACK_WEBHOOK_URL: '' } }
      },
      profiles: [],
      extraKeys: {}
    })
  })

  it('parses enabled channels, their values, profiles and preserves unknown keys verbatim (edge case)', () => {
    const raw = [
      'PORT=8080',
      'REDIS_URL=redis://localhost:6379',
      'RETRY_ATTEMPTS=5',
      'RETRY_BACKOFF_MS=2000',
      'CUSTOM_FLAG=on',
      'TOKENS=phone:tok123:ntfy,slack',
      'CHANNELS_ENABLED=ntfy',
      'NTFY_URL=https://ntfy.sh',
      'NTFY_TOPIC=mytopic',
      'SLACK_WEBHOOK_URL='
    ].join('\n')

    const cfg = parseAdminConfig(raw, registry)

    expect(cfg).toEqual({
      channels: {
        ntfy: { enabled: true, values: { NTFY_URL: 'https://ntfy.sh', NTFY_TOPIC: 'mytopic' } },
        slack: { enabled: false, values: { SLACK_WEBHOOK_URL: '' } }
      },
      profiles: [{ name: 'phone', token: 'tok123', defaultChannels: ['ntfy', 'slack'] }],
      extraKeys: {
        PORT: '8080',
        REDIS_URL: 'redis://localhost:6379',
        RETRY_ATTEMPTS: '5',
        RETRY_BACKOFF_MS: '2000',
        CUSTOM_FLAG: 'on'
      }
    })
  })

  it('ignores blank lines and comment lines', () => {
    const raw = ['# a comment', '', 'CHANNELS_ENABLED=ntfy', '  ', 'NTFY_URL=https://ntfy.sh', 'NTFY_TOPIC=t'].join(
      '\n'
    )

    const cfg = parseAdminConfig(raw, registry)

    expect(cfg.channels.ntfy).toEqual({ enabled: true, values: { NTFY_URL: 'https://ntfy.sh', NTFY_TOPIC: 't' } })
  })

  it('splits only on the first `=` so values containing `=` (e.g. query strings) stay intact', () => {
    const raw = 'CHANNELS_ENABLED=slack\nSLACK_WEBHOOK_URL=https://hooks.example.com?x=1&y=2'

    const cfg = parseAdminConfig(raw, registry)

    expect(cfg.channels.slack.values.SLACK_WEBHOOK_URL).toBe('https://hooks.example.com?x=1&y=2')
  })
})

describe('round-trip: parse(serialize(cfg)) deep-equals cfg', () => {
  it('round-trips a fully populated config', () => {
    const cfg: AdminConfig = {
      channels: {
        ntfy: { enabled: true, values: { NTFY_URL: 'https://ntfy.sh', NTFY_TOPIC: 'mytopic' } },
        slack: { enabled: false, values: { SLACK_WEBHOOK_URL: 'https://hooks.example.com/abc' } }
      },
      profiles: [
        { name: 'phone', token: 'tok123', defaultChannels: ['ntfy'] },
        { name: 'desktop', token: 'tok456', defaultChannels: [] }
      ],
      extraKeys: { PORT: '8080', REDIS_URL: 'redis://localhost:6379', CUSTOM_FLAG: 'on' }
    }

    const serialized = serializeAdminConfig(cfg, registry)
    const reparsed = parseAdminConfig(serialized, registry)

    expect(reparsed).toEqual(cfg)
  })

  it('round-trips the empty model produced from a missing file', () => {
    const cfg = parseAdminConfig(null, registry)

    const reparsed = parseAdminConfig(serializeAdminConfig(cfg, registry), registry)

    expect(reparsed).toEqual(cfg)
  })

  it('serialized output starts with the admin-panel-generated header comment', () => {
    const cfg = parseAdminConfig(null, registry)

    const serialized = serializeAdminConfig(cfg, registry)

    expect(serialized.split('\n')[0]).toMatch(/^# Generated by the notify-hub admin panel/)
  })
})
