/**
 * AdminConfig: the admin panel's view of `.env` (ADMIN-02, ADMIN-03). Parses
 * raw `.env` text into a structured model keyed by the channel registry's
 * `requiredConfig` schema (so parsing and channel building always agree on
 * which env keys belong to which channel -- same principle as
 * config/load-config.ts, just for editing rather than fail-fast loading).
 *
 * `serializeAdminConfig(parseAdminConfig(raw))` round-trips exactly (same
 * model back out), and any key not owned by CHANNELS_ENABLED/TOKENS/a
 * channel's requiredConfig is preserved verbatim in `extraKeys` (edge case:
 * PORT, REDIS_URL, RETRY_*, custom keys survive a rewrite untouched).
 *
 * TOKENS/CHANNELS_ENABLED format mirrors src/config/load-config.ts exactly
 * (`;`-separated `name:token:ch1,ch2` profiles; comma-separated channel
 * list) -- kept as small local parsers here so this module has no runtime
 * dependency on the gateway's fail-fast loader.
 */

export interface ChannelConfigEntry {
  enabled: boolean
  values: Record<string, string>
}

export interface AdminProfile {
  name: string
  token: string
  defaultChannels: string[]
}

export interface AdminConfig {
  channels: Record<string, ChannelConfigEntry>
  profiles: AdminProfile[]
  extraKeys: Record<string, string>
}

/** The slice of a ChannelRegistryEntry this module actually needs. */
export interface ChannelSchema {
  requiredConfig: string[]
}

const HEADER_COMMENT =
  '# Generated by the notify-hub admin panel -- manual edits/comments are ' +
  'overwritten on the next Save & Apply (a timestamped backup is kept).'

function parseCsv(raw: string): string[] {
  return raw
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
}

function parseTokens(raw: string): AdminProfile[] {
  return raw
    .split(';')
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0)
    .map((entry) => {
      const [name = '', token = '', channelsCsv = ''] = entry.split(':')
      return { name, token, defaultChannels: parseCsv(channelsCsv) }
    })
}

function serializeTokens(profiles: AdminProfile[]): string {
  return profiles
    .map((p) => `${p.name}:${p.token}:${p.defaultChannels.join(',')}`)
    .join(';')
}

/** Parses `KEY=VALUE` lines, ignoring blank lines and `#` comments. Splits on the FIRST `=` only, so values (URLs, tokens) may contain `=`. */
function parseEnvLines(raw: string): Record<string, string> {
  const result: Record<string, string> = {}
  for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (trimmed.length === 0 || trimmed.startsWith('#')) {
      continue
    }
    const eqIndex = trimmed.indexOf('=')
    if (eqIndex === -1) {
      continue
    }
    const key = trimmed.slice(0, eqIndex).trim()
    const value = trimmed.slice(eqIndex + 1).trim()
    if (key.length > 0) {
      result[key] = value
    }
  }
  return result
}

/**
 * Parses raw `.env` text (or null when the file doesn't exist yet) into an
 * AdminConfig, using `registry` as the schema for which env keys belong to
 * which channel. Missing file -> empty model (every registry channel
 * present but disabled with blank values, no profiles, no extra keys).
 */
export function parseAdminConfig(
  raw: string | null,
  registry: Record<string, ChannelSchema>
): AdminConfig {
  const rawMap = raw === null ? {} : parseEnvLines(raw)

  const enabledSet = new Set(parseCsv(rawMap.CHANNELS_ENABLED ?? ''))
  const reservedKeys = new Set(['CHANNELS_ENABLED', 'TOKENS'])

  const channels: Record<string, ChannelConfigEntry> = {}
  for (const [channelName, schema] of Object.entries(registry)) {
    const values: Record<string, string> = {}
    for (const key of schema.requiredConfig) {
      values[key] = rawMap[key] ?? ''
      reservedKeys.add(key)
    }
    channels[channelName] = { enabled: enabledSet.has(channelName), values }
  }

  const extraKeys: Record<string, string> = {}
  for (const [key, value] of Object.entries(rawMap)) {
    if (!reservedKeys.has(key)) {
      extraKeys[key] = value
    }
  }

  return {
    channels,
    profiles: parseTokens(rawMap.TOKENS ?? ''),
    extraKeys
  }
}

/**
 * Serializes an AdminConfig back to canonical `.env` text. `registry` fixes
 * channel/key iteration order so output is deterministic regardless of the
 * cfg object's own property insertion order. Order: header comment,
 * extraKeys, TOKENS, CHANNELS_ENABLED, then one block per registry channel.
 */
export function serializeAdminConfig(
  cfg: AdminConfig,
  registry: Record<string, ChannelSchema>
): string {
  const lines: string[] = [HEADER_COMMENT, '']

  for (const [key, value] of Object.entries(cfg.extraKeys)) {
    lines.push(`${key}=${value}`)
  }
  lines.push('', `TOKENS=${serializeTokens(cfg.profiles)}`)

  const enabledChannels = Object.entries(cfg.channels)
    .filter(([, entry]) => entry.enabled)
    .map(([name]) => name)
  lines.push(`CHANNELS_ENABLED=${enabledChannels.join(',')}`, '')

  for (const [channelName, schema] of Object.entries(registry)) {
    lines.push(`# --- ${channelName} ---`)
    const values = cfg.channels[channelName]?.values ?? {}
    for (const key of schema.requiredConfig) {
      lines.push(`${key}=${values[key] ?? ''}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}
